sudo: false
language: ruby
matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
    - rvm: jruby-9.1.0.0
    - rvm: 2.5.0
    - rvm: 2.4.1
    - rvm: 2.3.1
    - rvm: 2.2.0
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.0.0

before_install: gem install bundler -v 1.16.0
install: bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec
